CREATE DATABASE crudsimples DEFAULT CHARACTER SET UTF8 DEFAULT COLLATE;
USE crudsimples;

CREATE TABLE contato(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(45) NOT NULL,
	email VARCHAR(45) NOT NULL,
	celular VARCHAR(15) DEFAULT NULL,
	PRIMARY KEY(id)
);
